version: "1"
services:
  nn_profiler:
    image: nn_profiler
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #workspaces
      - ./container_root/:/container_root/
      - ./yolo-inference/:/container_root/yolo-inference/
      - ./onnxruntime/:/container_root/onnxruntime/
      - ./openvino_toolkit/:/container_root/openvino_toolkit/
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    entrypoint: /bin/bash
